# Generated by Django 5.1.4 on 2025-06-01 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managerpanel', '0013_student_completed_courses_alter_batch_cohort_and_more'),
        ('responseupload', '0006_alter_course_options_alter_courseresponse_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentManualCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_student_completions', to='responseupload.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_completions', to='managerpanel.student')),
            ],
            options={
                'verbose_name': 'Student Manual Course Completion',
                'verbose_name_plural': 'Student Manual Course Completions',
                'ordering': ['student', 'course__code'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
